### ISSUE TITLE
If you .collate() when there has been no output, subsequent .collate() fails afterwards once there is output

### ISSUE THREAD

**Issue by velocirobbie** [UCL-CCS/EasyVVUQ#163]
Will complain that column does not exist in SQL collaiton table

**Comment by velocirobbie** [comment]
(easyvvuq) robertsinclair@eduroam-int-dhcp-97-10-114 Materials $ python analyse_campaign.py 
Reloading campaign...
Traceback (most recent call last):
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1229, in _execute_context
    cursor, statement, parameters, context
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 549, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.OperationalError: table COLLATION_APP1 has no column named box_size
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "analyse_campaign.py", line 92, in <module>
    reloaded_campaign.collate()
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/easyvvuq-0.3.1+189.ga625314-py3.6.egg/easyvvuq/campaign.py", line 675, in collate
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/easyvvuq-0.3.1+189.ga625314-py3.6.egg/easyvvuq/collate/aggregate_samples.py", line 96, in collate
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/easyvvuq-0.3.1+189.ga625314-py3.6.egg/easyvvuq/collate/aggregate_samples.py", line 102, in append_data
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/easyvvuq-0.3.1+189.ga625314-py3.6.egg/easyvvuq/db/sql.py", line 799, in append_collation_dataframe
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/pandas/core/generic.py", line 2713, in to_sql
    method=method,
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/pandas/io/sql.py", line 518, in to_sql
    method=method,
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/pandas/io/sql.py", line 1320, in to_sql
    table.insert(chunksize, method=method)
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/pandas/io/sql.py", line 756, in insert
    exec_insert(conn, keys, chunk_iter)
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/pandas/io/sql.py", line 670, in _execute_insert
    conn.execute(self.table.insert(), data)
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1229, in _execute_context
    cursor, statement, parameters, context
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 549, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table COLLATION_APP1 has no column named box_size
[SQL: INSERT INTO "COLLATION_APP1" ("index", box_size, structure_no, replica_no, source_path, "X", "Y", "Z", run_id, ensemble_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ((0, 40, 1, 1, '/path/to/LAMMPS/data/files', 12722.097200849012, 42533.0714911846, 21306.28042386605, 'Run_1', 'Ensemble_1'), (1, 40, 1, 2, '/path/to/LAMMPS/data/files', 66273.06335141092, 27906.639132516328, 31878.23310428299, 'Run_2', 'Ensemble_2'), (2, 40, 1, 3, '/path/to/LAMMPS/data/files', 71451.25208969282, 65785.01886719263, -7883.293375044647, 'Run_3', 'Ensemble_3'), (3, 40, 1, 4, '/path/to/LAMMPS/data/files', 70582.8478312664, 41206.159831272256, 19487.86034380177, 'Run_4', 'Ensemble_4'), (4, 40, 1, 5, '/path/to/LAMMPS/data/files', 6647.464717459029, 11060.87291020169, 18800.924733191398, 'Run_5', 'Ensemble_5'), (5, 40, 1, 6, '/path/to/LAMMPS/data/files', 66318.4220975091, 11725.597214677831, 31191.653753767812, 'Run_6', 'Ensemble_6'), (6, 40, 1, 7, '/path/to/LAMMPS/data/files', 57755.93162572997, 35022.422920971854, 42127.56470656419, 'Run_7', 'Ensemble_7'), (7, 40, 1, 8, '/path/to/LAMMPS/data/files', 61409.07575669984, 35796.667625257614, 15179.464570771755, 'Run_8', 'Ensemble_8')  ... displaying 10 of 496 total bound parameter sets ...  (494, 30, 10, 9, '/path/to/LAMMPS/data/files', 24712.14294360021, 50282.743283456795, 42504.08237554907, 'Run_599', 'Ensemble_599'), (495, 30, 10, 10, '/path/to/LAMMPS/data/files', 26665.19534734802, 42570.71546518944, 3374.637104143972, 'Run_600', 'Ensemble_600'))]
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by raar1** [comment]
I'm going to deal with this now

**Comment by raar1** [comment]
I've fixed this in PR #176
