### ISSUE TITLE
setup.py should recompile cannonsim

### ISSUE THREAD

**Issue by velocirobbie** [UCL-CCS/EasyVVUQ#172]
when running tests, the executable cannonsim can get out of sync with the version of easyvvuq. 

Recompile cannonsm when `setup.py install` is run, or know to ignore cannonsim tests when it is an old version

**Comment by orbitfold** [comment]
One option would be to rewrite cannonsim in Python...

**Comment by velocirobbie** [comment]
Functionality to ignore cannonsim when it doesn't exist is already there
It's probably useful to show integration with something non-python

**Comment by orbitfold** [comment]
See PR #173

**Comment by velocirobbie** [comment]
This doesn't work for me, if cannonsim.cc is not up to date i get:
```
$ python setup.py install
/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/setuptools/dist.py:476: UserWarning: Normalizing 'v0.3.1+193.gff26557.dirty' to '0.3.1+193.gff26557.dirty'
  normalized_version,
running install
running bdist_egg
running egg_info
writing easyvvuq.egg-info/PKG-INFO
writing dependency_links to easyvvuq.egg-info/dependency_links.txt
writing requirements to easyvvuq.egg-info/requires.txt
writing top-level names to easyvvuq.egg-info/top_level.txt
reading manifest file 'easyvvuq.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'easyvvuq.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
running build_cannonsim
make: *** No rule to make target `cannonsim.cc', needed by `gmy2hgb'.  Stop.
Traceback (most recent call last):
  File "setup.py", line 62, in <module>
    include_package_data=True,
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/distutils/command/install_lib.py", line 105, in build
    self.run_command('build_py')
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 27, in run
    self.run_command('build_cannonsim')
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 22, in run
    subprocess.check_call(['make'], cwd=os.path.abspath('./tests/cannonsim/src'))
  File "/Users/robertsinclair/anaconda3/envs/easyvvuq/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
```

**Comment by orbitfold** [comment]
o_O

**Comment by orbitfold** [comment]
What does it do if you go to tests/cannonsim/src and run make manually?

**Comment by velocirobbie** [comment]
That works fine.....

**Comment by orbitfold** [comment]
And after that if you rerun python setup.py install it still fails?

**Comment by velocirobbie** [comment]
That's how i've got it to work

**Comment by velocirobbie** [comment]
I am an idiot, it was fine
