### ISSUE TITLE
Possible issue when running test script (basic_tutorial_qcgpj.py) in tutorials 

### ISSUE THREAD

**Issue by mzrghorbani** [UCL-CCS/EasyVVUQ#391]
**Running basic_tutorial_qcgpj.py terminates abruptly with the following message:**

```
 Traceback (most recent call last):
  File "basic_tutorial_qcgpj.py", line 44, in <module>
    campaign.campaign_db.dump()
  File "/home/mghorbani/workspace/FabSim/venv/lib/python3.8/site-packages/easyvvuq/db/sql.py", line 954, in dump
    result[table.name] = [dict(row) for row in self.engine.execute(table.select())]
AttributeError: 'Engine' object has no attribute 'execute'
```
Removing the line "campaign.campaign_db.dump()" will allow the execution to be completed successfully, however, it might have ramifications for handling db.

**Comment by mzrghorbani** [comment]
Fixed the issue with database dump and QC-GPJ execution in recent commits.

**Comment by DavidPCoster** [comment]
Seems to be fixed.
