### ISSUE TITLE
assertion failure while running easyvvuq_fusion_tutorial.py

### ISSUE THREAD

**Issue by DavidPCoster** [UCL-CCS/EasyVVUQ#412]
While running easyvvuq_fusion_tutorial.py, an assertion failure occurs:

...
Time for phase 3 = 75.534
Traceback (most recent call last):
  File "/gss_efgw_work/scratch/g2dpc/GIT/EasyVVUQ/tutorials/easyvvuq_fusion_tutorial.py", line 151, in <module>
    my_campaign.apply_analysis(
  File "/gss_efgw_work/scratch/g2dpc/GIT/EasyVVUQ/env_3.10/lib/python3.10/site-packages/easyvvuq-1.2.1+86.g46695a9.dirty-py3.10.egg/easyvvuq/campaign.py", line 617, in apply_analysis
    self.last_analysis = analysis.analyse(data_frame=self.get_collation_result())
  File "/gss_efgw_work/scratch/g2dpc/GIT/EasyVVUQ/env_3.10/lib/python3.10/site-packages/easyvvuq-1.2.1+86.g46695a9.dirty-py3.10.egg/easyvvuq/analysis/pce_analysis.py", line 478, in analyse
    dY_hat = build_surrogate_der(fit, verbose=False)
  File "/gss_efgw_work/scratch/g2dpc/GIT/EasyVVUQ/env_3.10/lib/python3.10/site-packages/easyvvuq-1.2.1+86.g46695a9.dirty-py3.10.egg/easyvvuq/analysis/pce_analysis.py", line 319, in build_surrogate_der
    assert(n1 == n2)
AssertionError

**Comment by DavidPCoster** [comment]
I haven't fixed the real underlying problem which arises from an assertion error in code from @goghino , but by wrapping the failing code in a try/except structure the analysis will succeed even though the "Sensitivity Analysis: Derivative based" code fails.  

For some value of T, 
 Y_hat[t].names <> Vars

Unless @goghino wants to look into the problem, I suggest we close this issue ...

**Comment by djgroen** [comment]
Closing it as @goghino didn't respond.
