### ISSUE TITLE
Error when number_of_replicas variable is set to 1 or 0

### ISSUE THREAD

**Issue by NicolasMonnier** [UCL-CCS/EasyVVUQ#74]
My script, based on the example script `run_workflow.py`, raised an error when I set the number of replicas to 1 or 0. (or even when don't initiate any replicas variable).

The replica's initiation look like the following lines

```
number_of_replicas = 1 (or = 0)
replicator = uq.elements.sampling.Replicate(my_campaign, replicates=number_of_replicas)
my_campaign.add_runs(replicator)

```

The (long) error : 
```
Traceback (most recent call last):
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/core/groupby/groupby.py", line 2670, in agg_series
    return self._aggregate_series_fast(obj, func)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/core/groupby/groupby.py", line 2690, in _aggregate_series_fast
    result, counts = grouper.get_result()
  File "pandas/_libs/reduction.pyx", line 420, in pandas._libs.reduction.SeriesGrouper.get_result
  File "pandas/_libs/reduction.pyx", line 404, in pandas._libs.reduction.SeriesGrouper.get_result
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/core/groupby/groupby.py", line 1062, in <lambda>
    f = lambda x: func(x, *args, **kwargs)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/easyvvuq-0.0.1.dev1-py3.6.egg/easyvvuq/elements/analysis/ensemble_boot.py", line 116, in <lambda>
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/easyvvuq-0.0.1.dev1-py3.6.egg/easyvvuq/elements/analysis/ensemble_boot.py", line 92, in bootstrap
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/easyvvuq-0.0.1.dev1-py3.6.egg/easyvvuq/elements/analysis/ensemble_boot.py", line 65, in confidence_interval
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/numpy-1.12.1-py3.6-linux-x86_64.egg/numpy/lib/function_base.py", line 4116, in percentile
    interpolation=interpolation)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/numpy-1.12.1-py3.6-linux-x86_64.egg/numpy/lib/function_base.py", line 3828, in _ureduce
    a = np.asanyarray(a)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/numpy-1.12.1-py3.6-linux-x86_64.egg/numpy/core/numeric.py", line 583, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/core/series.py", line 767, in __getitem__
    result = self.index.get_value(self, key)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/core/indexes/base.py", line 3118, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas/_libs/index.pyx", line 106, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 114, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 958, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 964, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_workflow_nbody.py", line 82, in <module>
    results, output_file = ensemble_boot.apply()
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/easyvvuq-0.0.1.dev1-py3.6.egg/easyvvuq/elements/analysis/base.py", line 116, in apply
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/easyvvuq-0.0.1.dev1-py3.6.egg/easyvvuq/elements/analysis/ensemble_boot.py", line 208, in _apply_analysis
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/easyvvuq-0.0.1.dev1-py3.6.egg/easyvvuq/elements/analysis/ensemble_boot.py", line 122, in ensemble_bootstrap
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/core/groupby/groupby.py", line 4656, in aggregate
    return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/core/groupby/groupby.py", line 4087, in aggregate
    result, how = self._aggregate(arg, _level=_level, *args, **kwargs)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/core/base.py", line 490, in _aggregate
    result = _agg(arg, _agg_1dim)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/core/base.py", line 441, in _agg
    result[fname] = func(fname, agg_how)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/core/base.py", line 424, in _agg_1dim
    return colg.aggregate(how, _level=(_level or 0) + 1)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/core/groupby/groupby.py", line 3492, in aggregate
    return self._python_agg_general(func_or_funcs, *args, **kwargs)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/core/groupby/groupby.py", line 1068, in _python_agg_general
    result, counts = self.grouper.agg_series(obj, f)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/core/groupby/groupby.py", line 2672, in agg_series
    return self._aggregate_series_pure_python(obj, func)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/core/groupby/groupby.py", line 2703, in _aggregate_series_pure_python
    res = func(group)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/core/groupby/groupby.py", line 1062, in <lambda>
    f = lambda x: func(x, *args, **kwargs)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/easyvvuq-0.0.1.dev1-py3.6.egg/easyvvuq/elements/analysis/ensemble_boot.py", line 116, in <lambda>
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/easyvvuq-0.0.1.dev1-py3.6.egg/easyvvuq/elements/analysis/ensemble_boot.py", line 92, in bootstrap
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/easyvvuq-0.0.1.dev1-py3.6.egg/easyvvuq/elements/analysis/ensemble_boot.py", line 65, in confidence_interval
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/numpy-1.12.1-py3.6-linux-x86_64.egg/numpy/lib/function_base.py", line 4116, in percentile
    interpolation=interpolation)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/numpy-1.12.1-py3.6-linux-x86_64.egg/numpy/lib/function_base.py", line 3828, in _ureduce
    a = np.asanyarray(a)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/numpy-1.12.1-py3.6-linux-x86_64.egg/numpy/core/numeric.py", line 583, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/core/series.py", line 767, in __getitem__
    result = self.index.get_value(self, key)
  File "/home_nfs_robin_ib/bmonniern/VECMA/install_EasyVVUQ_intel_19.1.144/lib/python3.6/site-packages/pandas-0.23.4-py3.6-linux-x86_64.egg/pandas/core/indexes/base.py", line 3118, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas/_libs/index.pyx", line 106, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 114, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 958, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 964, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0

```

Is it a 'real' error or having no replicas makes no sense ? (or something else?)

**Comment by dww100** [comment]
@NicolasMonnier This is a real error - our plan is to fix as part of the refactoring we are doing now.

**Comment by dww100** [comment]
In the refactored version for M12 this is fixed for some use cases by adding a replica option to the sample drawing method.

The replacement of the old replicate sampler is now a separate issue (#90) and will be dealt with after M12 release.
